name             'stash'
maintainer       'Appriss Inc.'
maintainer_email 'dsledge@appriss.com'
license          'All rights reserved'
description      'Installs/Configures stash'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 	 'labrea'
depends		 'java'
depends      'newrelic'
